security:
    encoders:
        Acme\DemoBundle\Entity\User:
            algorithm: sha512

    role_hierarchy:
        ROLE_STUDENT: ROLE_USER
        ROLE_TEACHER: [ ROLE_USER, ROLE_STUDENT]
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: AcmeDemoBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _security_check
                login_path: _demo_login
                use_referer: true
            logout:
                path:   _demo_logout
                target: _demo
                invalidate_session: false
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
